# feeder
feeder: feeder.Feeder
test_feeder_args:
  mode: test
  window_size: 250
  data_path: ./data/val_joint.npy
  label_path: ./data/val_label.npy

# model
model: net.ST_GCN
model_args:
  num_class: 10
  channel: 3
  window_size: 250
  num_point: 20
  graph: graph.Ucla
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True 

# test 
phase: test
device: 0
test_batch_size: 64
weights: ./model


