work_dir: ./work_dir/

# feeder
feeder: feeder.Feeder
train_feeder_args:
  mode: train
  data_path: ./data/train_images.npy
  label_path: ./data/train_masks.npy
test_feeder_args:
  mode: test
  data_path: ./data/test_images.npy
  label_path: ./data/test_masks.npy

# model
model: net.ULite
model_args:
  num_class: 4
  channel: 3

#optim
optimizer: Adam
base_lr: 1e-2
L2_REG: 1e-4

# training
device: cuda
batch_size: 16
test_batch_size: 16
num_worker: 4
num_epoch: 500
nesterov: True